### ISSUE TITLE
Virtuoso 7 support

### ISSUE THREAD

**Issue by propi** [dbpedia/dbpedia-vad-i18n#11]
Is it possible to build this DBpedia package within Virtuoso 7 (develop or stable branch)?

I tried it but the VAD file wasn't created during making virtuoso and package sources. In version 6 (develop) I don't have any problem. When I want to make the DBpedia package I get only this message: Nothing to be done for `all' . Virtuoso sources are made successfully but packages not. Any ideas?

**Comment by jimkont** [comment]
check the ./configure options, you need to specify the packages you want in
advance

**Comment by propi** [comment]
Ok, thank you! I used this feature: ./configure --enable-dbpedia-vad and I didn't have any problem with making and installing the DBpedia package within Virtuoso 7/develop
