### ISSUE TITLE
xsd:gMonthDay is presented as an xsd:date with a year of 0001

### ISSUE THREAD

**Issue by josephw** [dbpedia/dbpedia-vad-i18n#13]
Many dates in dbpedia are stored as `xsd:gMonthDay`, with no year:

```
dbpedia:The_Archers
dbpprop:firstAired  "--05-29+02:00"^^xsd:gMonthDay , "--01-01+02:00"^^xsd:gMonthDay ;
```

This is [presented on the web](http://dbpedia.org/page/The_Archers) as:

<table>
<tr>
<td>dbpprop:firstAired</td>
<td>
<ul>
<li>0001-01-01 (xsd:date)
<li>0001-05-29 (xsd:date)
</ul>
</td>
</tr>
</table>

Giving the impression that a year is set.

**Comment by jimkont** [comment]
This is a virtuoso issue where it losses sone specific data types

**Comment by josephw** [comment]
Is there somewhere to track this issue in Virtuoso?

**Comment by jimkont** [comment]
There is an issue for gYear and for a few other datatypes here
https://github.com/openlink/virtuoso-opensource/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+datatype

I know there has been some progress but no details
